
simbot:
  core:
    # 机器人的账号密码
    bots:
      - 2199386146:232020ctt
  component:
    mirai:
      # mirai心跳周期. 过长会导致被服务器断开连接. 单位毫秒。
      heartbeat-period-millis: 30000
      # 每次心跳时等待结果的时间.一旦心跳超时, 整个网络服务将会重启 (将消耗约 1s). 除正在进行的任务 (如图片上传) 会被中断外, 事件和插件均不受影响.
      heartbeat-timeout-millis: 5000
      # 心跳失败后的第一次重连前的等待时间.
      first-reconnect-delay-millis: 5000
      # 重连失败后, 继续尝试的每次等待时间
      reconnect-period-millis: 5000
      # 最多尝试多少次重连
      reconnection-retry-times: 2147483647
      # 使用协议类型。注，此值为枚举类 net.mamoe.mirai.utils.BotConfiguration.MiraiProtocol 的元素值，
      # 可选值为：ANDROID_PHONE、ANDROID_PAD、ANDROID_WATCH
      protocol: ANDROID_PAD
      # 是否关闭mirai的bot logger
      no-bot-log: true
      # 关闭mirai网络日志
      no-network-log: true
      # mirai bot log切换使用simbot的log
      use-simbot-bot-log: true
      # mirai 网络log 切换使用simbot的log
      use-simbot-network-log: true
      # mirai配置自定义deviceInfoSeed的时候使用的随机种子。默认为1.
      device-info-seed: 1
      # mirai图片缓存策略，为枚举 love.forte.simbot.component.mirai.configuration.MiraiCacheType 的元素值，
      # 可选为 FILE、 MEMORY
      cache-type: MEMORY
      # 如果配置项 simbot.mirai.cacheType 的值为 FILE，此处为缓存文件的保存目录。为空时默认为系统临时文件夹。
      cache-directory:
      # 登录验证码处理器，当登录需要输入验证码的时候可能会用到。
      login-solver-type: DEFAULT
      # 如果不为空，此处代表指定一个 deviceInfo 的 json文件路径。
      dispatcher:
        # mirai组件中，对事件进行调度的线程池参数：最大线程数。
        core-pool-size: 8
        # mirai组件中，对事件进行调度的线程池参数：最大线程数。
        maximum-pool-size: 8
        # mirai组件中，对事件进行调度的线程池参数：线程存活时间（毫秒）
        keep-alive-time: 1000





spring:
  datasource:
    url: jdbc:mysql://rm-uf6e4xr978w748b9w7o.mysql.rds.aliyuncs.com:3306/xiaoka_robot?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: "xys"
    password: "232020ctt@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    #username: 2879322503@qq.com
    #password: gkemyvdhkfoudgij
    username: 2199386146@qq.com
    password: vlwtxgyxpkdgdjaa
    test-connection: false
    properties:
      mail:
        smtp:
          auth: false
        debug: false
        mime:
          splitlongparameters: false
    default-encoding: UTF-8



mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定默认枚举类型的类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
      # 查询，如果比较的字段为null或者""，则不会当作条件取查询
      select-strategy: not_empty
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml
  # MyBatis-plus在进行更新操作时不会更新传入实体中为null或默认值属性字段，只更新不为null的值、非默认值的属性字段。

